# To choose a Python version, first create the env with:
# conda create -n tensorframes python=3.6
# and then update it
name: tensorframes
channels:
- https://repo.anaconda.com/pkgs/main/linux-64/
dependencies:
- pandas=0.23.4
- nomkl
- tensorflow=1.12.0
# test
- nose=1.3.7
